theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo_eeafsb_black.svg'
    footer: '/assets/images/logo_eeafsb_black.svg'
  posts:
    index:
      layout: list
      options:
        author: false
        date: false
        image: false
