theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  posts:
    index:
      layout: list
      options:
        author: false
        date: false
        image: false
